run_tests:
  before_script:
    - echo "Preparing test data..."
  script:
    - echo "Running test..."
  after_script:
    - echo "Cleaning up temporary files..."

build_image:
  script:
    - echo "Building the docker image..."

push_image:
  script:
    - echo "Logging into docker registry..."
    - echo "Pushing docker image to registry..."